kind: Secret
apiVersion: v1
metadata:
  name: backend-secret
  namespace: app
type: Opaque

stringData:
  jwt-secret: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc4NjUxNDA5NywiaWF0IjoxNzg2NTE0MDk3fQ.mRxhmV5gAHlskfp9gQnA-D1MH23a2BgDRhjjlvS9ynE"
